# Generated by Django 2.1.5 on 2019-01-09 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('0', 'Adelaide'), ('1', 'Albury'), ('2', 'AliceSprings'), ('3', 'BadgerysCreek'), ('4', 'Ballarat'), ('5', 'Bendigo'), ('6', 'Brisbane'), ('7', 'Cairns'), ('8', 'Canberra'), ('9', 'Cobar'), ('10', 'CoffsHarbour'), ('11', 'Dartmoor'), ('12', 'Darwin'), ('13', 'GoldCoast'), ('14', 'Hobart'), ('15', 'Katherine'), ('16', 'Launceston'), ('17', 'Melbourne'), ('18', 'MelbourneAirport'), ('19', 'Mildura'), ('20', 'Moree'), ('21', 'MountGambier'), ('22', 'MountGinini'), ('23', 'Nhil'), ('24', 'NorahHead'), ('25', 'NorfolkIsland'), ('26', 'Nuriootpa'), ('27', 'PearceRAAF'), ('28', 'Penrith'), ('29', 'Perth'), ('30', 'PerthAirport'), ('31', 'Portland'), ('32', 'Richmond'), ('33', 'Sale'), ('34', 'SalmonGums'), ('35', 'Sydney'), ('36', 'SydneyAirport'), ('37', 'Townsville'), ('38', 'Tuggeranong'), ('39', 'Uluru'), ('40', 'WaggaWagga'), ('41', 'Walpole'), ('42', 'Watsonia'), ('43', 'Williamtown'), ('44', 'Witchcliffe'), ('45', 'Wollongong'), ('46', 'Woomera')], max_length=40)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('wind_gust_dir', models.CharField(choices=[('0', 'E'), ('1', 'ENE'), ('2', 'ESE'), ('3', 'N'), ('4', 'NE'), ('5', 'NNE'), ('6', 'NNW'), ('7', 'NW'), ('8', 'S'), ('9', 'SE'), ('10', 'SSE'), ('11', 'SSW'), ('12', 'SW'), ('13', 'W'), ('14', 'WNW'), ('15', 'WSW')], max_length=10)),
                ('wind_gust_speed', models.FloatField()),
                ('wind_dir_9am', models.CharField(choices=[('0', 'E'), ('1', 'ENE'), ('2', 'ESE'), ('3', 'N'), ('4', 'NE'), ('5', 'NNE'), ('6', 'NNW'), ('7', 'NW'), ('8', 'S'), ('9', 'SE'), ('10', 'SSE'), ('11', 'SSW'), ('12', 'SW'), ('13', 'W'), ('14', 'WNW'), ('15', 'WSW')], max_length=10)),
                ('wind_dir_3pm', models.CharField(choices=[('0', 'E'), ('1', 'ENE'), ('2', 'ESE'), ('3', 'N'), ('4', 'NE'), ('5', 'NNE'), ('6', 'NNW'), ('7', 'NW'), ('8', 'S'), ('9', 'SE'), ('10', 'SSE'), ('11', 'SSW'), ('12', 'SW'), ('13', 'W'), ('14', 'WNW'), ('15', 'WSW')], max_length=10)),
                ('wind_speed_9am', models.FloatField()),
                ('wind_speed_3pm', models.FloatField()),
                ('humidity_9am', models.FloatField()),
                ('humidity_3pm', models.FloatField()),
                ('temp_9am', models.FloatField()),
                ('temp_3pm', models.FloatField()),
                ('rain_today', models.BooleanField()),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
